//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Models
{
	/// <summary>
	/// Database       : ivmsmaintain
	/// Data Source    : localhost
	/// Server Version : 5.5.25
	/// </summary>
	public partial class IvmsmaintainDB : LinqToDB.Data.DataConnection
	{
		public ITable<IvmsLine>       IvmsLine       { get { return this.GetTable<IvmsLine>(); } }
		public ITable<IvmsServer>     IvmsServer     { get { return this.GetTable<IvmsServer>(); } }
		public ITable<Station>        Stations       { get { return this.GetTable<Station>(); } }
		public ITable<TServerManager> TServerManager { get { return this.GetTable<TServerManager>(); } }

		public IvmsmaintainDB()
		{
			InitDataContext();
		}

		public IvmsmaintainDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("ivms_line")]
	public partial class IvmsLine
	{
		[Column(@"id"),       PrimaryKey, Identity] public uint   Id       { get; set; } // int(10) unsigned
		[Column(@"name"),     NotNull             ] public string Name     { get; set; } // varchar(255)
		[Column(@"stations"), NotNull             ] public string Stations { get; set; } // varchar(1000)
		[Column(@"path"),     NotNull             ] public string Path     { get; set; } // varchar(255)
	}

	[Table("ivms_server")]
	public partial class IvmsServer
	{
		[Column(@"id"),          Nullable] public int?   Id          { get; set; } // int(11)
		[Column(@"gwid"),        Nullable] public string Gwid        { get; set; } // varchar(255)
		[Column(@"type"),        Nullable] public int?   Type        { get; set; } // int(11)
		[Column(@"address"),     Nullable] public string Address     { get; set; } // varchar(255)
		[Column(@"strip"),       Nullable] public int?   Strip       { get; set; } // int(11)
		[Column(@"pri_prefix"),  Nullable] public string PriPrefix   { get; set; } // varchar(255)
		[Column(@"attrs"),       Nullable] public string Attrs       { get; set; } // varchar(255)
		[Column(@"probe_mode"),  Nullable] public int?   ProbeMode   { get; set; } // int(11)
		[Column(@"state"),       Nullable] public int?   State       { get; set; } // int(11)
		[Column(@"socket"),      Nullable] public string Socket      { get; set; } // varchar(255)
		[Column(@"description"), Nullable] public string Description { get; set; } // varchar(255)
		[Column(@"sourceIp"),    Nullable] public string SourceIp    { get; set; } // varchar(255)
	}

	[Table("stations")]
	public partial class Station
	{
		[Column(@"PK_ID"),         PrimaryKey,  Identity] public int    PKID         { get; set; } // int(11)
		[Column(),                    Nullable          ] public int?   ID           { get; set; } // int(11)
		[Column(),                 NotNull              ] public string NAME         { get; set; } // varchar(255)
		[Column(@"LINE_NAME"),        Nullable          ] public string LINENAME     { get; set; } // varchar(255)
		[Column(@"STATION_PATH"),     Nullable          ] public string STATIONPATH  { get; set; } // varchar(255)
		[Column(),                    Nullable          ] public string SERVER       { get; set; } // varchar(255)
		[Column(@"CONVERGE_IP"),      Nullable          ] public string CONVERGEIP   { get; set; } // varchar(255)
		[Column(@"CONVERGE_NAME"),    Nullable          ] public string CONVERGENAME { get; set; } // varchar(255)
	}

	[Table("t_server_manager")]
	public partial class TServerManager
	{
		[Column(@"PK_ID"), PrimaryKey, Identity] public int    PKID         { get; set; } // int(11)
		[Column(),         Nullable            ] public string StationNo    { get; set; } // varchar(255)
		[Column(),         Nullable            ] public string Ip           { get; set; } // varchar(255)
		[Column(),         Nullable            ] public string StationName  { get; set; } // varchar(255)
		[Column(),         Nullable            ] public string Line         { get; set; } // varchar(255)
		[Column(),         Nullable            ] public string Path         { get; set; } // varchar(255)
		[Column(),         Nullable            ] public string ConvergeIp   { get; set; } // varchar(255)
		[Column(),         Nullable            ] public string ConvergeName { get; set; } // varchar(255)
	}

	public static partial class TableExtensions
	{
		public static IvmsLine Find(this ITable<IvmsLine> table, uint Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Station Find(this ITable<Station> table, int PKID)
		{
			return table.FirstOrDefault(t =>
				t.PKID == PKID);
		}

		public static TServerManager Find(this ITable<TServerManager> table, int PKID)
		{
			return table.FirstOrDefault(t =>
				t.PKID == PKID);
		}
	}
}
